name: Build GTK Frontend

on: [push]

jobs:
  GTK-Frontend:
    name: 'GTK Frontend'
    
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build and package
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: Proximity.flatpak
          manifest-path: com.forensant.proximity.yml
          cache-key: flatpak-builder-${{ github.sha }}  
  
      - name: Upload build
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Proximity.flatpak
          # A file, directory or wildcard pattern that describes what to upload
          path: Proximity.flatpak