name: Build GTK Frontend

on: [push]

jobs:
  HTML-Frontend:
    name: 'HTML Frontend'

    runs-on: ubuntu-latest

    steps:
      - name: Clone Pākiki HTML Frontend
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'forensant'
          repository: 'pakiki-frontend-html'

      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Node dependencies
        working-directory: 'pakiki-frontend-html'
        run: npm install
        
      - name: Build the frontend
        working-directory: 'pakiki-frontend-html'
        run: npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v2.2.3
        with:
          name: pakiki-frontend-html
          # A file, directory or wildcard pattern that describes what to upload
          path: pakiki-frontend-html/dist

  Pakiki-Core:
    name: 'Pākiki Core'
    runs-on: ubuntu-22.04
    
    needs: HTML-Frontend
      
    steps:
      - name: Clone Pākiki Core
        uses: actions/checkout@v3
        with:
          repository: forensant/pakiki-core
          submodules: recursive
          path: pakiki-core

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      
      - name: Download frontend
        uses: actions/download-artifact@v2
        with:
          name: pakiki-frontend-html
          path: pakiki-core/www/html_frontend/dist/
            
      - name: Install system dependencies
        run: sudo apt install build-essential

      - name: Install golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.
        
      - name: Build golang executable
        working-directory: pakiki-core
        run: |
          go install github.com/swaggo/swag/cmd/swag
          ./scripts/build.sh

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file

      - name: Copy Dependencies
        working-directory: pakiki-core/build
        run: ../scripts/copy_lib_linux.rb ./

      - name: List files and their types (for debug)
        working-directory: pakiki-core/build
        run: |
          ls -lah

      - name: Set permissions
        working-directory: pakiki-core
        run: chmod +x build/*

      - name: Upload core build
        uses: actions/upload-artifact@v2.2.3
        with:
          name: pakiki-core
          # A file, directory or wildcard pattern that describes what to upload
          path: pakiki-core/build

  GTK-Frontend-Flatpak:
    name: 'GTK Frontend Flatpak'
    needs: Pakiki-Core
    
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download core
        uses: actions/download-artifact@v2
        with:
          name: pakiki-core
          path: pakiki-core

      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat src/resources/version)"

      - name: Build and package
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: Pakiki-Proxy-Community-v${{ steps.getversion.outputs.version }}-Linux-x64.flatpak
          manifest-path: com.forensant.pakiki-github.yml
          cache-key: flatpak-builder-${{ github.sha }}  

  GTK-Frontend-Deb:
    name: 'GTK Frontend - .deb'
    needs: Pakiki-Core
    
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download core
        uses: actions/download-artifact@v2
        with:
          name: pakiki-core
          path: pakiki-core

      - name: Update system repositories
        run: sudo apt update

      - name: Install system dependencies
        run: sudo apt install build-essential valac meson libgtk-3-dev libsoup-3.0-dev libjson-glib-dev libwebkit2gtk-4.1-dev libgtksourceview-3.0-dev libgee-0.8-dev libnotify-dev

      - name: Create Debian build
        run: ./build-for-debian.sh

      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat src/resources/version)"

      - uses: jiro4989/build-deb-action@v2
        with:
          package: Pakiki
          package_root: .debpkg
          maintainer: Forensant
          version: ${{ steps.getversion.outputs.version }} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'libc6 (>= 2.2.1), libgtk-3-0, libpython3.11, libsoup-3.0-0, libjson-glib-1.0-0, libwebkit2gtk-4.1-0, libgtksourceview-3.0-1, libgee-0.8-2, libnotify4'
          desc: 'Native next generation intercepting proxy, designed for security testing of web applications.'

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-deb
          path: |
            ./*.deb
            
